changesetBaseRefs:
  - origin/main

defaultSemverRangePrefix: ""

packageExtensions:
  "@codemirror/lang-html@*":
    dependencies:
      "@codemirror/view": "*"
  "@lezer/css@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/html@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": "*"
  react-devtools-inline@*:
    dependencies:
      react-is: "*"
      scheduler: "*"
    peerDependencies:
      react: "*"
      react-dom: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
